### ISSUE TITLE
Fastrun and CrazySpeed styles?

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#183] opened 2016-08-28 18:01 UTC
Fastrun - you run with 2000 velocity in the start zone so you jump off with 2k speed.
Example video: https://www.youtube.com/watch?v=4lnEZe037Vs

CrazySpeed - you gain +250 velocity every next jump (1st jump you gain +250 = 500 velocity, 2nd jump 750 velocity, 3rd jump 1000 velocity... and so on.)
Example video: https://www.youtube.com/watch?v=UGgX3dr8gLw

I know someone that has the CS 1.6 code for CrazySpeed but not for Fastrun :/
If you need that code, I'm gonna try to contact this guy, cuz he wasn't on steam since 2 years.
I'm not even sure if it's gonna be possible in the Source engine.

**Comment by Technoblazed** [comment] 2016-08-28 18:21
You did choose some pretty aidsy videos, q.q

**Comment by shavitush** [comment] 2016-08-28 18:49
About the first one, I don't think it's possible

For the second one, you could integrate this plugin with the timer's API very easily: https://forums.alliedmods.net/showthread.php?t=57900

It shouldn't be more than adding below this:

    #define STYLE_260PRESTRAFE	(1 << 17) // 260 prestrafe instead of the default 250; requires dhooks and shavit_misc_staticprestrafe 1.

The following line:

    #define STYLE_CRAZYSPEED	(1 << 37) // crazyspeed

And in the plugin I linked, it could be edited to do that: (didn't test compilation, should work. and obviously, change the cvars so they will be what you consider as crazyspeed)

```
/* BunnyHop
* Author: Soccerdude
* Description: Gives players the ability to jump higher
*/
#include <sourcemod>
#include <sdktools>

#undef REQUIRE_PLUGIN
#define USES_STYLE_PROPERTIES
#include <shavit>

#pragma semicolon 1

// Declare offsets

new VelocityOffset_0;
new VelocityOffset_1;
new BaseVelocityOffset;

// Declare convar handles

new Handle:hPush;
new Handle:hHeight;

public Plugin:myinfo = 
{
  name = "BunnyHop",
  author = "Soccerdude",
  description = "Gives players the ability to jump higher",
  version = "1.0.1",
  url = "http://sourcemod.net/"
};

public OnPluginStart()
{
  PrintToServer("----------------|         BunnyHop Loading        |---------------");
  // Hook Events
  HookEvent("player_jump",PlayerJumpEvent);
  // Find offsets
  VelocityOffset_0=FindSendPropOffs("CBasePlayer","m_vecVelocity[0]");
  if(VelocityOffset_0==-1)
    SetFailState("[BunnyHop] Error: Failed to find Velocity[0] offset, aborting");
  VelocityOffset_1=FindSendPropOffs("CBasePlayer","m_vecVelocity[1]");
  if(VelocityOffset_1==-1)
    SetFailState("[BunnyHop] Error: Failed to find Velocity[1] offset, aborting");
  BaseVelocityOffset=FindSendPropOffs("CBasePlayer","m_vecBaseVelocity");
  if(BaseVelocityOffset==-1)
    SetFailState("[BunnyHop] Error: Failed to find the BaseVelocity offset, aborting");
  // Create cvars
  hPush=CreateConVar("bunnyhop_push","1.0","The forward push when you jump");
  hHeight=CreateConVar("bunnyhop_height","1.0","The upward push when you jump");
  // Create config
  AutoExecConfig();
  // Public cvar
  CreateConVar("bunnyhop_version","1.0.1","[BunnyHop] Current version of this plugin",FCVAR_PLUGIN|FCVAR_SPONLY|FCVAR_UNLOGGED|FCVAR_DONTRECORD|FCVAR_REPLICATED|FCVAR_NOTIFY);
  PrintToServer("----------------|         BunnyHop Loaded         |---------------");
}

public PlayerJumpEvent(Handle:event,const String:name[],bool:dontBroadcast)
{
  new index=GetClientOfUserId(GetEventInt(event,"userid"));

  if(!(gI_StyleProperties[Shavit_GetBhopStyle(client)] & STYLE_CRAZYSPEED))
  {
	  return;
  }
  
  new Float:finalvec[3];
  finalvec[0]=GetEntDataFloat(index,VelocityOffset_0)*GetConVarFloat(hPush)/2.0;
  finalvec[1]=GetEntDataFloat(index,VelocityOffset_1)*GetConVarFloat(hPush)/2.0;
  finalvec[2]=GetConVarFloat(hHeight)*50.0;
  SetEntDataVector(index,BaseVelocityOffset,finalvec,true);
}
```

I just really don't think it needs to be a base feature of the plugin as it was intended to be used in CS:S/CS:GO bhop servers and as a player, I've never seen those styles myself.

**Comment by Nickelony** [comment] 2016-08-28 19:04
This could be a very nice feature when out of beta :)

BTW I have some problems compiling this:

```
//// crazyspeed.sp
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(40) : warning 234: symbol "FindSendPropOffs" is marked as deprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check for existence.
//
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(43) : warning 234: symbol "FindSendPropOffs" is marked as deprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check for existence.
//
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(46) : warning 234: symbol "FindSendPropOffs" is marked as deprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check for existence.
//
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(55) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in the first hl2sdk.
//
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(63) : error 017: undefined symbol "client"
//
// 1 Error.
//
// Compilation Time: 1,22 sec
// ----------------------------------------
```

**Comment by shavitush** [comment] 2016-08-28 19:05
my bad, fixed it now

**Comment by Nickelony** [comment] 2016-08-28 19:07
```
//// crazyspeed.sp
//
// C:\Users\Nickelony\Desktop\sourcemod-1.8.0-git5928-windows\addons\sourcemod\scripting\crazyspeed.sp(55) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in the first hl2sdk.
//
//
// Code size:             5144 bytes
// Data size:             3868 bytes
// Stack/heap size:      16384 bytes
// Total requirements:   25396 bytes
//
// 1 Warning.
//
// Compilation Time: 0,17 sec
```

Will it work now? or will this warning kill it?

**Comment by shavitush** [comment] 2016-08-28 19:10
you can fix it by replacing `FCVAR_PLUGIN` with `0` but it should work

**Comment by Nickelony** [comment] 2016-08-28 19:23
This plugins works on every style, not only STYLE_CRAZYSPEED. What should I do?

**Comment by StrafeHack** [comment] 2016-08-29 13:04
The first one is quite similar to prespeed style at least after the start zone. You could just configure sv_noclipspeed to go to 2000

**Comment by Nickelony** [comment] 2016-09-01 20:41
Since I don't think this is going to be a thing, I'm closing this. Thanks for your help :)

**Comment by Nickelony** [comment] 2016-09-10 23:03
I'm sorry, I know I shouldn't ask you to do that but I've been trying for almost 3 hours to get the CrazySpeed style to work with the new shavit-styles.cfg but since I have 0 knowledge about programming (and I'm a retard aswell) could you try to do it for me please? x(

**Comment by Nickelony** [comment] 2016-09-11 09:19
I've been trying all night, but all I got is this: http://pastebin.com/raw/2Hmrh2Fh

I still get lots of errors :/

**Comment by Technoblazed** [comment] 2016-09-11 09:22
Including dynamic would be a start.

**Comment by Nickelony** [comment] 2016-09-11 09:26
I have 0 knowledge about that.
I'll learn programming in a year or 2 depending on my teachers. That sucks ._.
At least I tried. RIP CrazySpeed :(

**Comment by shavitush** [comment] 2016-09-11 11:20
Use the 'special' property and assign it to... 32 and use this code for 'crazyspeed'

```sp
#include <sourcemod>
#include <sdktools>

#undef REQUIRE_PLUGIN
#include <shavit>

#pragma newdecls required
#pragma semicolon 1

any gA_StyleSettings[STYLE_LIMIT][STYLESETTINGS_SIZE];

// Declare offsets
new VelocityOffset_0;
new VelocityOffset_1;
new BaseVelocityOffset;

// Declare convar handles

new Handle:hPush;
new Handle:hHeight;

bool gB_Late = false;

public Plugin:myinfo = 
{
  name = "BunnyHop",
  author = "Soccerdude",
  description = "Gives players the ability to jump higher",
  version = "1.0.1",
  url = "http://sourcemod.net/"
};

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
	gB_Late = late;

	return APLRes_Success;
}

public void Shavit_OnStyleConfigLoaded(int styles)
{
	if(styles == -1)
	{
		styles = Shavit_GetStyleCount();
	}

	for(int i = 0; i < styles; i++)
	{
		Shavit_GetStyleSettings(view_as<BhopStyle>(i), gA_StyleSettings[i]);
	}
}

public OnPluginStart()
{
  PrintToServer("----------------|         BunnyHop Loading        |---------------");
  // Hook Events
  HookEvent("player_jump",PlayerJumpEvent);
  // Find offsets
  VelocityOffset_0=FindSendPropInfo("CBasePlayer","m_vecVelocity[0]");
  if(VelocityOffset_0==-1)
    SetFailState("[BunnyHop] Error: Failed to find Velocity[0] offset, aborting");
  VelocityOffset_1=FindSendPropInfo("CBasePlayer","m_vecVelocity[1]");
  if(VelocityOffset_1==-1)
    SetFailState("[BunnyHop] Error: Failed to find Velocity[1] offset, aborting");
  BaseVelocityOffset=FindSendPropInfo("CBasePlayer","m_vecBaseVelocity");
  if(BaseVelocityOffset==-1)
    SetFailState("[BunnyHop] Error: Failed to find the BaseVelocity offset, aborting");
  // Create cvars
  hPush=CreateConVar("bunnyhop_push","0.4","The forward push when you jump");
  hHeight=CreateConVar("bunnyhop_height","0.0","The upward push when you jump");
  // Create config
  AutoExecConfig();
  // Public cvar
  CreateConVar("bunnyhop_version","1.0.1","[BunnyHop] Current version of this plugin",0|FCVAR_SPONLY|FCVAR_UNLOGGED|FCVAR_DONTRECORD|FCVAR_REPLICATED|FCVAR_NOTIFY);
  PrintToServer("----------------|         BunnyHop Loaded         |---------------");
}

public void OnMapStart()
{
	if(gB_Late)
	{
		Shavit_OnStyleConfigLoaded(-1);
	}
}

public PlayerJumpEvent(Handle:event,const String:name[],bool:dontBroadcast)
{
  new index=GetClientOfUserId(GetEventInt(event,"userid"));

  if(gA_StyleSettings[Shavit_GetBhopStyle(index)][iSpecial] == 32)
  {
      return;
  }

  new Float:finalvec[3];
  finalvec[0]=GetEntDataFloat(index,VelocityOffset_0)*GetConVarFloat(hPush)/2.0;
  finalvec[1]=GetEntDataFloat(index,VelocityOffset_1)*GetConVarFloat(hPush)/2.0;
  finalvec[2]=GetConVarFloat(hHeight)*50.0;
  SetEntDataVector(index,BaseVelocityOffset,finalvec,true);
}
```

**Comment by Nickelony** [comment] 2016-09-11 11:41
THANK YOU ;DDDDDDD

**Comment by Nickelony** [comment] 2016-09-11 11:55
uumm...

```
//// crazyspeed.sp
//
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(13) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(14) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(15) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(19) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(20) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(24) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(53) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(86) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(86) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(88) : error 147: new-style declarations are required
// C:\Users\Nickelony\Desktop\scripting\crazyspeed.sp(95) : error 147: new-style declarations are required
//
// 11 Errors.
//
// Compilation Time: 0,41 sec
// ----------------------------------------
```

**Comment by shavitush** [comment] 2016-09-11 13:05
whoops, edited

**Closed** 2016-09-11 15:54 UTC
