### ISSUE TITLE
Ranking/Point system

### ISSUE THREAD

**Issue by Vikingvrede** [shavitush/bhoptimer#338] opened 2017-04-15 17:58 UTC
Hello, i can't get ranking/Points to work. i have seen servers who use your plugin and ranks aswell as points seems to be working fine for them. I have looked at forum posts and looked at other "!Issues" on github. 

Does it only work with local mysql? ( stored on server, i use external btw) 
Or is it only working with sqlite.
Plugin still under maintenance?

**Comment by Technoblazed** [comment] 2017-04-15 18:00
- Ranking / points are broken in the current version, there is a temporary patch on the alliedmods forum to patch them.
- It supports external  mysql connections.
- Plugin development has stopped.

**Comment by Vikingvrede** [comment] 2017-04-15 18:03
Thanks @Technoblazed , Could you send link to patch?
Sad to hear that development has stopped. =(

**Comment by Technoblazed** [comment] 2017-04-15 18:27
https://forums.alliedmods.net/showpost.php?p=2480830&postcount=960

It's highly experimental, backup your database and don't say you werent warned  :^)

**Comment by elleven11** [comment] 2017-04-17 19:24
Suggest to use stamm instead of that...

**Comment by theSaint92** [comment] 2017-04-18 14:00
What's that? (stamm)

**Comment by Technoblazed** [comment] 2017-04-18 15:00
http://lmgtfy.com/?q=sourcemod+stamm+plugin

**Comment by elleven11** [comment] 2017-04-20 13:14
I tried to make an ez plugin that gives you stamm points when you finish the timer.

But it gives me error 100 on the stamm includes...

(I give up)

**Comment by shavitush** [comment] 2017-06-03 20:13
Stamm isn't a rankings plugin and isn't a suitable alternative. I'll try to work on rankings again soon.

**Comment by shavitush** [comment] 2017-08-02 03:14
Duplicate of #154.

**Closed by shavitush** 2017-08-02 03:14 UTC
Labels: duplicate
