### ISSUE TITLE
[verygoodyes] Limit how much replaybots player can spawn(and max bots on server)

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#1039] opened 2021-03-24 18:10 UTC
![image](https://user-images.githubusercontent.com/17723060/112362103-5f9cd080-8cd4-11eb-96c0-2ab27de7d62d.png)
Atm you can spawn as many bots as you want. Add a cvar for maximum bots per player untill they're over and max running replaybots at the same time on server.

**Comment by cytrus224** [comment] 2021-03-24 18:51
I might have missed the cvar, but its not working anyway
![image](https://user-images.githubusercontent.com/17723060/112367488-4434c400-8cda-11eb-8670-7d49b266645f.png)

**Comment by rtldg** [comment] 2021-03-25 02:26
Fixed `shavit_replay_dynamicbotlimit` not working in https://github.com/shavitush/bhoptimer/commit/807cbc6dfef1065b09d5283f71b434eb37f4b6e0

> Changing it to 0 disables also centralbot.

I can't reproduce this.

Still need to make it so a player can only spawn one dynamic bot at a time though and then I'll close this issue after I do that

**Comment by rtldg** [comment] 2021-04-12 17:31
Fixed players being able to start multiple simultaneous dynamic bots. I don't think it's worth adding a cvar for max bots on the server when that can be done by changing the dynamicbotlimit cvar and disabling looping bot configs.

**Closed** 2021-05-01 01:11 UTC
