### ISSUE TITLE
Broken advertisements?

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#271] opened 2016-10-06 20:56 UTC
When I set the advertisement interval to 60.0, it shows a message randomly from 2 to 30 sec. Is it intentional?

**Comment by shavitush** [comment] 2016-10-06 21:08
nope; can you show me your related settings/config files and i'll try to reproduce it?

**Comment by Technoblazed** [comment] 2016-10-07 16:36
puu.sh in 2016 *shakes head*

**Comment by Nickelony** [comment] 2016-10-07 16:38
What's wrong with puu.sh? I'm still using the old client, but the new ShareX isn't that bad. :P

**Comment by Technoblazed** [comment] 2016-10-07 16:40
puu.sh is known for shady stuff, sharex has plenty of other alternatives for file hosting :D

**Comment by shavitush** [comment] 2016-10-07 17:50
puu.sh is owned by peppy and peppy is known for hiding stuff like full monitor screenshotting without the users' knowledge; was found out when his osu! source code got leaked even though he claimed that it was removed and the leak contained up to date screenshots

anyways: i'll take a look at it soon

**Comment by Nickelony** [comment] 2016-10-09 08:28
I've noticed that the more players are on the server, the more intense the spam gets. When there are 20 players on the server, the advertisements gotta go fast :D

I think you forgot to make them client sided.

**Comment by shavitush** [comment] 2016-10-14 15:52
Let me know if it's solved! @Nickelony

**Comment by Nickelony** [comment] 2016-10-14 16:36
Found some glitches:
1. The records are completely broken as well as the bot names after the "public" update: https://puu.sh/rINQr.jpg

2. https://puu.sh/rINW0.png - the zone colors are still broken. "NoLimit" and "Teleport" share the same colors and "Freestyle" is yellow and invisible. (idk from which glitch zone)

3. The advertisements work fine, but they disappear after map change for some reason.

**Comment by shavitush** [comment] 2016-10-14 16:40
I know about the zone colors, that's why we have another issue for them!

I'll check the problem regarding the public update, hopefully will be solved today.

**Comment by shavitush** [comment] 2016-10-14 16:46
Cannot replicate broken records in my server :/ Can you check your error logs and maybe restart your server?

**Comment by Nickelony** [comment] 2016-10-14 16:48
I think that was a mysql problem... doesn't happen anymore.

BTW only the first advertisements appears, the rest is gone. :P

**Comment by shavitush** [comment] 2016-10-14 17:10
Try reverting `shavit-wr` to the previous version and let me know if it's the issue

**Comment by shavitush** [comment] 2016-10-14 17:17
Oh, I know what's causing your issue: clients with the SteamID `STEAM_ID_PENDING` because of the latest CS:GO update. Either shut down your server or wait for psychonic's update of SourceMod. https://forums.alliedmods.net/showpost.php?p=2461973&postcount=92

**Comment by Nickelony** [comment] 2016-10-16 20:54
The SM update fixed the records, but what's with the advertisements? It shows one every 10 minutes, even if the cvar is set to 60 sec.

**Comment by shavitush** [comment] 2016-10-17 00:02
oh.. I know what to do! I'll fix it today or tomorrow :)

**Comment by shavitush** [comment] 2016-10-25 07:34
Fixed within #280

**Closed by shavitush** 2016-10-25 07:34 UTC
Labels: bug
