### ISSUE TITLE
Unknown column 'rowid' in 'field list'

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#406] opened 2017-07-18 15:47 UTC
This might be something I messed up no clue but sometimes when going to a map zoned or unzoned this error is given and if the map is zoned none of them load.
`[shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: Unknown column 'rowid' in 'field list'`

**Comment by shavitush** [comment] 2017-07-18 15:52
My fault, that's because I tested on SQLite and `rowid` doesn't exist in MySQL.

**Comment by shavitush** [comment] 2017-07-19 10:32
Can you see if the issue is fixed now? I can't reproduce it on my end anymore.

**Comment by strafe** [comment] 2017-07-19 15:55
@shavitush seems like the only thing that sets `gB_DBReady` to true is not being called at all, so the zones are not loaded.

**Comment by shavitush** [comment] 2017-07-22 17:36
Test again please! Haven't had the chance to test but this solution seems better.

**Comment by strafe** [comment] 2017-07-22 20:55
Yep it works, that's what I did in the meantime to fix it too, just feels kind of a hacky way to fix it.

**Closed** 2017-07-22 21:48 UTC
Labels: bug, high priority

**Comment by strafe** [comment] 2017-07-22 22:40
@shavitush should there also be a similar else statement in SQL_AlterTable2_Callback? What if the table needs to be altered and completes successfully, won't gB_DBReady still be false?

**Comment by shavitush** [comment] 2017-07-22 23:17
It won't matter, because `gB_DBReady` is being put in an `if()` statement only in OnMapStart()!
