### ISSUE TITLE
Style categories (Style sorting) + 1 style issue

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#362] opened 2017-06-15 09:34 UTC
Something like this: https://puu.sh/wkDig.png

If you want the code for this, here you go: https://www.diffchecker.com/7Py7kkjP
You just need to modify it slightly so it can be configured with a .cfg file instead of modifying the plugin.
You also need to sort the sm_wr menu.

Oh and add this to shavit.inc: (you don't have to if you find an easier way to handle this)

```
enum
{
	iCategory,
	iSortOrdner,
	bAutobhop,
	bEasybhop,
	bPrespeed,
```

Edit: I found an issue with the styles.
If you have more than 24 styles, the style commands (sm_nm, sm_normal etc.) stop working for every style that's above "24".

**Comment by strafe** [comment] 2017-06-15 13:04
@Nickelony don't you think that's quite messy and confusing?

I think the approach Mehis used is much more user-friendly and cleaner visually, the _Modes_ are displayed at the top of the !style menu and the _Styles_ follow with a gap between them. The one you're suggesting is similar to Zipcore's "Ranked and Unranked" categories.

Here are the first 2 pages of the style menu:

![image](https://user-images.githubusercontent.com/15663890/27182475-21578bfc-51d3-11e7-98ad-aacf79edb930.png)
![image](https://user-images.githubusercontent.com/15663890/27182483-26b5e4fe-51d3-11e7-924f-e7f81527c345.png)

**Comment by Nickelony** [comment] 2017-06-15 13:31
I think style categories are much faster and much easier to use instead of going through pages like this. Our server has over 30 styles and the style categories are very useful in this situation.

**Comment by Technoblazed** [comment] 2017-06-15 14:42
Sounds more like a personal server idea rather than a full plugin ideq

**Comment by shavitush** [comment] 2017-06-15 16:39
@Nickelony I never had to add 24 styles to a server so.. never noticed this issue! I'll try working on a solution soon.

@strafe I'll implement it so !style will show your current style and won't let you select your current style, thanks for the screenshots!

**Comment by PaxPlay** [comment] 2017-06-16 18:10
I'd make it so you can toggle specific predefined things such as autobhop, parcour, lowgrav, tas/tsa(if you really wanna add it) or stuff like that per style, and that the actual styles are just things that block certain movements/keypresses, tho specific things should not be allowed to be enabled on specific styles (also configurable in a cfg).

For example, when choosing W-Only you can toggle auto OFF and lowgrav on.

Besides me actually wanting to kill everyone desiring to play W-Only lowgrav scroll, this would be a way better and more elegant solution for handling styles in my opinion.

**Comment by shavitush** [comment] 2017-06-17 04:17
@PaxPlay, this feature exists for at least half a year.. https://github.com/shavitush/bhoptimer/blob/master/configs/shavit-styles.cfg

**Comment by shavitush** [comment] 2017-06-17 04:22
@Nickelony just went through the code and I cannot figure out what causes the >28 styles issue, sorry. Help will be appreciated on this one.

**Comment by strafe** [comment] 2017-06-17 12:41
@shavitush it must be related to the total length of all style commands? Nickelony originally said it doesn't work with more than 24 styles, you said it doesn't work with more than 28.

When using style entries like this I was able to use 30+ styles just fine:
```
	"30"
	{
		"name"				"30"
		"shortname"			"30"
		"htmcolor"			"FFFFFF"
		"command"			"30"
		
		"noreplay"			"1"
		
		"unranked"			"1"
	}
```

However, when I changed my entries to the ones below I couldn't use anything over 21 styles.
```
	"30"
	{
		"name"				"30"
		"shortname"			"30"
		"htmcolor"			"FFFFFF"
		"command"			"3030303030"
		
		"noreplay"			"1"
		
		"unranked"			"1"
	}
```

**Comment by shavitush** [comment] 2017-06-17 14:56
28 was actually a typo, I meant 24 (which is the number Nickelony used). What about this configuration, @Nickelony - does it solve your issue?

   char gS_StyleStrings[STYLE_LIMIT][STYLESTRINGS_SIZE][512];

And

    dStyle.GetString("command", gS_StyleStrings[i][sChangeCommand], 128);

\>>

    dStyle.GetString("command", gS_StyleStrings[i][sChangeCommand], 512);

And change the part that starts with `if(!gB_Registered` to:

```
if(!gB_Registered && strlen(gS_StyleStrings[i][sChangeCommand]) > 0)
{
	char[][] sStyleCommands = new char[256][256];
	int iCommands = ExplodeString(gS_StyleStrings[i][sChangeCommand], ";", sStyleCommands, 256, 256, false);

	char[] sDescription = new char[192];
	FormatEx(sDescription, 192, "Change style to %s.", gS_StyleStrings[i][sStyleName]);

	for(int x = 0; x < iCommands; x++)
	{
		TrimString(sStyleCommands[x]);
		StripQuotes(sStyleCommands[x]);

		char[] sCommand = new char[128];
		FormatEx(sCommand, 128, "sm_%s", sStyleCommands[x]);

		gSM_StyleCommands.SetValue(sCommand, i);

		RegConsoleCmd(sCommand, Command_StyleChange, sDescription);
	}
}
```

**Comment by strafe** [comment] 2017-06-17 15:17
Hmm, regardless it was still 21 for me personally with the large commands. I just tried with the code you posted above and the problem is still there. The command string is already malformed when fetched.
```
dStyle.GetString("command", gS_StyleStrings[i][sChangeCommand], 512);
PrintToServer(gS_StyleStrings[i][sChangeCommand]);
```
![test](https://user-images.githubusercontent.com/15663890/27254056-2facc298-5378-11e7-918c-16ad7f7e268a.png)
[Style Config](https://pastebin.com/VFTP7TQ1)

**Comment by shavitush** [comment] 2017-06-18 08:09
I cannot replicate the issue at all..

![2017-06-18_11-07-42](https://user-images.githubusercontent.com/3672466/27259228-74116684-5416-11e7-8235-cb70e7e60b16.png)

Do you guys maybe use an outdated version of Dynamic?

**Comment by strafe** [comment] 2017-06-18 11:19
Updated Dynamic, even though I'm quite sure I was already using the latest version on GitHub. I've tried with fresh installs of both master and development and both still have this problem for me.

**Comment by Technoblazed** [comment] 2017-06-18 11:23
1. Are you both using the same game?
2. Could it be the length of the file? Perhaps just try the config that shavit is using strafe.

**Comment by strafe** [comment] 2017-06-18 11:35
@Technoblazed thanks for suggesting that, I just tried my style config on CS:S and it works, so does shavit's. But on CS:GO shavit's works and mine still does not.

**Comment by strafe** [comment] 2017-07-15 21:42
Finally got around to testing this myself. Freshly installed LAN server, nothing was transferred, I downloaded MM, SM and all dependencies again and compiled from the latest commit in bugfixes using all default settings and only replacing the style config that I posted in an earlier comment and I got the exact same result.

(I also tried with the default shavit-core and with the changes shavit posted in an earlier comment and both yield this result.)

![image](https://user-images.githubusercontent.com/15663890/28242846-ac925448-69ae-11e7-88cb-882004d22c19.png)

**Comment by shavitush** [comment] 2017-07-16 06:52
Could it be that your server is hitting a memory usage limit?

**Comment by strafe** [comment] 2017-07-16 13:22
No idea I tested it on my Linux server and my windows PC and it happens the exact same way.

**Comment by shavitush** [comment] 2017-07-28 03:16
@strafe - can you test after applying commit d3a0d5b7f9bc58d269e14b85b3196b0625a5b64f? It removes Dynamic as a dependency and might fix this issue.

**Comment by strafe** [comment] 2017-07-28 04:32
Still the same sadly 😞 
```SourcePawn
kv.GetString("command", gS_StyleStrings[i][sChangeCommand], 128, "");
kv.GetString("clantag", gS_StyleStrings[i][sClanTag], 128, "<MISSING STYLE CLAN TAG>");
PrintToServer("%s", gS_StyleStrings[i][sChangeCommand]);
```
![image](https://user-images.githubusercontent.com/15663890/28702626-1af76d14-7356-11e7-8266-a4d4437b9682.png)

**Comment by shavitush** [comment] 2017-07-28 05:04
Well, that sucks. Have you tried updating your SourceMod and Metamod: Source to the latest stable releases?

**Comment by strafe** [comment] 2017-07-28 05:07
I'll test on CS:GO and CS:S with 1.8 and 1.9 at some point today and post the results but I expect them to be the same... since the test I did 12 days ago was on the latest stable release at that time.

**Comment by shavitush** [comment] 2017-07-28 05:29
Revisited by me. CS:S, Windows.

```
meta version
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/4a27e2f
Build ID: 959:4a27e2f
Loaded As: Valve Server Plugin
Compiled on: Dec 22 2015
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/
sm version
 SourceMod Version Information:
    SourceMod Version: 1.8.0.6015
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6015)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jul  6 2017 12:16:00
    Built from: https://github.com/alliedmodders/sourcemod/commit/b94620e
    Build ID: 6015:b94620e
    http://www.sourcemod.net/
```

```
sm plugins list
[SM] Listing 16 plugins:
  01 "Admin File Reader" (1.8.0.6015) by AlliedModders LLC
  02 "Admin Menu" (1.8.0.6015) by AlliedModders LLC
  03 "Basic Commands" (1.8.0.6015) by AlliedModders LLC
  04 "[bhopstats] Bunnyhop Statistics API" (1.2.0) by shavit
  05 "noslide" (1.0) by shavit
  06 "[shavit] Core" (1.5b) by shavit
  07 "[shavit] HUD" (1.5b) by shavit
  08 "[shavit] Miscellaneous" (1.5b) by shavit
  09 "[shavit] Replay Bot" (1.5b) by shavit
  10 "[shavit] Sounds" (1.5b) by shavit
  11 "[shavit] Player Stats" (1.5b) by shavit
  12 "[shavit] Dynamic Timelimits" (1.5b) by shavit
  13 "[shavit] World Records" (1.5b) by shavit
  14 "[shavit] Map Zones" (1.5b) by shavit
  15 "[shavit] SSJ: Advanced" (1.5.0) by AlkATraZ
  16 "Unreal Physics (bhoptimer module)" (1.3) by blacky
```

Config file: https://gist.github.com/1027fa091364073f8d241d0760ee638f

![image](https://user-images.githubusercontent.com/3672466/28703647-339b1006-736e-11e7-8e5c-5f1401134775.png)

**Comment by strafe** [comment] 2017-07-28 05:58
```
meta version
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/4a27e2f
Build ID: 959:4a27e2f
Loaded As: Valve Server Plugin
Compiled on: Apr 26 2017
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/
sm version
SourceMod Version Information:
    SourceMod Version: 1.8.0.6015
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6015)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jul  6 2017 12:16:00
    Built from: https://github.com/alliedmodders/sourcemod/commit/b94620e
    Build ID: 6015:b94620e
    http://www.sourcemod.net/
```
```
sm plugins list
[SM] Listing 11 plugins:
  01 "Client Preferences" (1.8.0.6015) by AlliedModders LLC
  02 "[shavit] Core" (1.5b) by shavit
  03 "[shavit] HUD" (1.5b) by shavit
  04 "[shavit] Miscellaneous" (1.5b) by shavit
  05 "[shavit] Replay Bot" (1.5b) by shavit
  06 "[shavit] Sounds" (1.5b) by shavit
  07 "[shavit] Player Stats" (1.5b) by shavit
  08 "[shavit] Dynamic Timelimits" (1.5b) by shavit
  09 "[shavit] World Records" (1.5b) by shavit
  10 "[shavit] Map Zones" (1.5b) by shavit
  11 "Basic Commands" (1.8.0.6015) by AlliedModders LLC
```
![image](https://user-images.githubusercontent.com/15663890/28704390-35ffd770-7362-11e7-8c7b-bc3649828398.png)
![image](https://user-images.githubusercontent.com/15663890/28704393-392de27a-7362-11e7-96f9-59bbcc70b9c1.png)

**Comment by shavitush** [comment] 2017-07-28 06:00
Can you provide me with the `shavit-styles.cfg` from the second screenshot?

**Comment by strafe** [comment] 2017-07-28 06:09
https://pastebin.com/p2E6TrGP

**Comment by shavitush** [comment] 2017-07-28 07:34
I can't reproduce, welp. 
![image](https://user-images.githubusercontent.com/3672466/28707167-f43195d6-737f-11e7-81a1-fb7964bdc452.png)

However, I thought about that CS:GO's (yes, SourceMod does calls to Source Engine functions, and one of them is KeyValues) implementation of KeyValues automatically detects something as an `int32` as long as it doesn't contain letters.

Can you try adding letters to the 27, 29 and 30 styles to see if it parses them correctly like that?

**Comment by strafe** [comment] 2017-07-28 07:37
Yep looks like you figured it out 😄 
![image](https://user-images.githubusercontent.com/15663890/28707347-eee8ec60-736f-11e7-98e9-88d3d03b4037.png)

**Comment by shavitush** [comment] 2017-07-28 07:43
Glad to see it's nothing on the plugin's fault haha.. I guess this can be closed then!

**Closed by shavitush** 2017-07-28 07:43 UTC
Labels: bug, help wanted
