### ISSUE TITLE
shavit_misc_prespeed 1 Not working!

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#331] opened 2017-02-26 13:37 UTC
If you fly with noclip through the texture, and a second before, to start it off, the speed is not reset!

**Comment by Technoblazed** [comment] 2017-02-26 13:46
https://github.com/shavitush/bhoptimer/issues/286

Issue exists. Duplicate.

**Comment by T1MOXA** [comment] 2017-02-26 13:52
Yes, I saw but the question is old, and there is no solution, so I created a new one!

**Comment by Technoblazed** [comment] 2017-02-26 14:36
Plugin development has been stopped, so there's honestly no need to.

**Comment by T1MOXA** [comment] 2017-02-27 00:23
Where info about it?

**Comment by Technoblazed** [comment] 2017-02-27 00:31
https://forums.alliedmods.net/showthread.php?p=2477362#post2477362

**Comment by Technoblazed** [comment] 2017-02-27 00:31
I think there was another post somewhere after that, but not sure where it is.

**Comment by T1MOXA** [comment] 2017-02-27 00:37
:(
Thanks for information.
I hope he'll be back soon :)

**Comment by shavitush** [comment] 2017-06-03 18:39
Duplicate of #286.

**Closed by shavitush** 2017-06-03 18:39 UTC
Labels: duplicate
